### PR TITLE
Unix socket by default

### LINKED ISSUE #125: Connecting via default unix socket without username/password
Hello! I have the following settings in my pg_hba.conf:

```conf
local   all             all                                     peer
host    all             all             127.0.0.1/32            md5
```

That allows me to connect to any database via unix socket without authentication, but when I connect via `localhost` I am asked for password.

I.e., I can run

```shell
$ createdb test
$ psql test
connected
```

and be connected. Please note that by default `psql` (`libpq`, perhaps?) connects via unix socket; also note `psql` doesn't require username. If I want to connect via localhost I have to do it explicitly:

```shell
$ psql -h localhost test
Password:
```

I can also connect via non-standard unix socket, the option is also `-h host`:

```shell
$ psql -h /run/postgresql test
connected
```

Only directory is required. Driver `psycopg2` follows the conventions (perhaps because they are imposed by `libpq` and `psycopg2` uses `libpq`):

```python
con = psycopg2.connect(database="test")  # connected
```

```python
con = psycopg2.connect(database="test", host='/run/postgresql')  # connected
```

Unfortunately, pg8000 doesn't follow these conventions:

```python
con = pg8000.connect(database="test")

Traceback (most recent call last):
  File "./test_pg8000.py", line 7, in <module>
    con = pg8000.connect(database="test")
  File "/home/phd/.tox/SQLObject/py27-pg8000/local/lib/python2.7/site-packages/pg8000/__init__.py", line 105, in connect
    user, host, unix_sock, port, database, password, ssl, timeout)
  File "/home/phd/.tox/SQLObject/py27-pg8000/local/lib/python2.7/site-packages/pg8000/core.py", line 1231, in __init__
    "The 'user' connection parameter cannot be None")
pg8000.core.InterfaceError: The 'user' connection parameter cannot be None
```

```python
con = pg8000.connect(database="test", user='')

Traceback (most recent call last):
  File "./test_pg8000.py", line 8, in <module>
    con = pg8000.connect(database="test", user='')
  File "/home/phd/.tox/SQLObject/py27-pg8000/local/lib/python2.7/site-packages/pg8000/__init__.py", line 105, in connect
    user, host, unix_sock, port, database, password, ssl, timeout)
  File "/home/phd/.tox/SQLObject/py27-pg8000/local/lib/python2.7/site-packages/pg8000/core.py", line 1607, in __init__
    raise e
pg8000.core.InterfaceError: md5 password authentication failed
```

Seems like I'm connecting via localhost, not unix socket.

```python
con = pg8000.connect(database="test", user='',
                     unix_sock='/var/run/postgresql/.s.PGSQL.5432')

Traceback (most recent call last):
  File "./test_pg8000.py", line 10, in <module>
    unix_sock='/var/run/postgresql/.s.PGSQL.5432')
  File "/home/phd/.tox/SQLObject/py27-pg8000/local/lib/python2.7/site-packages/pg8000/__init__.py", line 105, in connect
    user, host, unix_sock, port, database, password, ssl, timeout)
  File "/home/phd/.tox/SQLObject/py27-pg8000/local/lib/python2.7/site-packages/pg8000/core.py", line 1607, in __init__
    raise e
pg8000.core.InterfaceError: md5 password authentication failed
```

Ouch! What is going on? What username must be passed?

Can pg8000 be fixed so that

```python
con = pg8000.connect(database="test")
```

connects via default unix socket, without username/password?

### PR DESCRIPTION
**Pull request by phdru**
Connect via default unix socket on systems that support unix sockets, else `localhost`. Use the current OS user name. Fix #125.

### CODE REVIEW

**Comment by phdru** [comment]
The errors are not mine, I think. There errors from flake8. I can fix them but I don't know what would be the best way — to insert required empty lines or to disable the error in setup.cfg.

Errors with pypy3 are strange — it seems it requires pip for python >= 3.3. Don't know how to fix that.

**Comment by mfenniak** [comment]
Hey @phdru, thanks for the pull request.  I have a few concerns I'd like to discuss about this PR, though.

I'm a little concerned about the backwards compatibility here of changing default behaviour.  Existing users of the library could easily be broken by this upgrade.  Do you have any thoughts on how this without potentially breaking current users?

I'm not a big fan of hard-coding the path "/var/run/postgresql/.s.PGSQL.5432".  At a minimum, it should incorporate the `port` setting.  But, the path that makes sense as a default to me would actually be "/tmp/.s.PGSQL.${port}" (see: https://www.postgresql.org/docs/9.5/static/libpq-connect.html#LIBPQ-CONNECT-HOST); this would match the default of libpq when Postgres is not otherwise configured to a non-default location.  What's the rationale for you on using this port location?

**Comment by phdru** [comment]
> I'm a little concerned about the backwards compatibility here of changing default behaviour. Existing users of the library could easily be broken by this upgrade. Do you have any thoughts on how this without potentially breaking current users?

Oops, no. That's an incompatible change, really.

> the path that makes sense as a default to me would actually be "/tmp/.s.PGSQL.${port}"

I never saw /tmp/ as the path for the socket. On all systems I remember the path is either /var/run/postgresql/ or /run/postgresql/ (on more recent Linux distributions /var/run is a symlink to /run, so those are the same).

**Comment by mfenniak** [comment]
With regard to the socket path, PostgreSQL's vendor default is ```/tmp```.  It can be overridden at server build-time, or by changing the ```unix_socket_directories``` property in postgresql.conf.  Libraries that link to libpq automatically get access to the build-time configured default, which is handy for them... but for pg8000 we'd be supporting a random selection of Linux distros (generally Debian-derived) by hard-coding ```/var/run/postgresql```.

Because this is a breaking change, and it unfortunately can't be implemented with the correctness of a built-time libpq-based implementation, I'm favouring not merging this.  I appreciate the effort you put in to send in a pull request, and there's nothing wrong with the patch functionally, but the fix isn't valuable enough for the problem it might cause any existing users.

**Comment by phdru** [comment]
Can I ask you to merge 4 other commits from the PR other than related to unix socket? The last one is especially important.

**Pull request closed without merging**
