### PR TITLE
Fix #113. Don't rollback when not in a transaction.

### LINKED ISSUE #113: "WARNING: not in a transaction" difference from psycopg2 and workaround
I'm one of the maintainers of [RelStorage](http://relstorage.readthedocs.io), a relational-database backend for [ZODB](http://zodb.readthedocs.io).

RelStorage has supported running on PostgreSQL for a long time (in fact it was originally *only* PG), always using the `psycopg2` driver (and lately the `psycopg2cffi` driver). I've [been working](https://github.com/zodb/relstorage/pull/98) to add support for pg8000 (it has many advantages like being gevent compatible, which I also maintain).

First, thanks for the awesome library. It was a snap to take the psycopg2 code and get it working with pg8000. Amazing work! RelStorage's extensive test suite runs without a flaw.

Well, there is one tiny flaw. When using pg8000, the PostgreSQL server generates *hundreds* of messages: "WARNING: not in a transaction". 

I turned on statement logging, and discovered that these were always due to a COMMIT immediately followed by a ROLLBACK. This is a sequence that RelStorage has in some cases, and the nature of RelStorage makes that a difficult scenario to avoid.

psycopg2 handles this natively in the client by simply not sending the rollback if the connection state isn't in a transaction. Here's the code for its python version, psycopg2cffi:
```python
    def _rollback(self):
        with self._lock:
            if self._autocommit or self.status != consts.STATUS_BEGIN:
                return
            self._mark += 1
            try:
                self._execute_command('ROLLBACK')
            finally:
                self.status = consts.STATUS_READY
```

In looking at pg8000, I noticed the Connection keeps track of a `in_transaction` variable. I modified RelStorage [to subclass Connection](https://github.com/zodb/relstorage/blob/d94b8415e4472d55811a91bc6298651c6d39a854/relstorage/adapters/_postgresql_drivers.py#L177) and use that variable to do the same thing, and the warnings stopped, while the tests continue to pass. I was happy.
```python
    class _DoesNotRollbackIfNotInTransaction(pg8000.Connection):

        def rollback(self):
            if not self.in_transaction:
                return
            return super(_DoesNotRollbackIfNotInTransaction,self).rollback()
```

So I was wondering if this is a good idea, or if there's some reason that it wouldn't be? If it is a good idea, is this an enhancement you'd be willing to add to pg8000 itself? I can do a PR if that would be helpful.

### PR DESCRIPTION
**Pull request by jamadden**
I didn't see a good place to add a test specifically for this but I can if somebody shows me the way.

### CODE REVIEW

**Comment by mfenniak** [comment]
`pg8000/tests/test_query.py` looks like the best place we'd have to add a test.

**Comment by jamadden** [comment]
Sure. I guess what I meant to say was I don't see *how* to add a test. There aren't any specific tests of Connection internal state I could spot, nor are there any mocks or similar in place at the socket level to check what gets sent to the database.

My go-to for this sort of test would perhaps be to mock the `execute` method to record the operations it performs, and verify that they don't contain a ROLLBACK, something like:

```python
def test(self):
    conn = ...
    cursor = conn.cursor()
    commands = []
    conn_execute = conn.execute
    conn.execute = lambda s, cur, op, vals: commands.append(op)
    self.assertFalse(conn.in_transaction)
    conn.rollback()
    self.assertEqual([], commands)
    del conn.execute
    cursor.execute('select ...')
    self.assertTrue(conn.in_transaction)
    conn.execute = lambda s, cur, op, vals: commands.append(op)
    conn.rollback()
    self.assertEqual(['rollback]', commands)
```
But that sort of pattern doesn't appear to be in use here, so I didn't know if there was some other preferred way of checking internal state and command executions, other than as a side-effect of the session state...which seems to implicitly verify that this at least doesn't break anything

**Comment by mfenniak** [comment]
Oh, oh yes, that's obviously much more interesting.  Sorry for the lame response. :-)

I believe that the driver will receive the "WARNING:  there is no transaction in progress" message when you perform a double-rollback, and it will fire the `NoticeReceived` event on the connection.  (https://github.com/mfenniak/pg8000/blob/9dfad86f4caab48e303f464dae1966d698a92ffa/pg8000/core.py#L1292).  The docs on this property show how to subscribe to it and the data that will be received.

With that in hand, you should be able to write a test that performs two calls to rollback(), and verifies it does not receive the warning notice.  The test should fail without your change, and pass with it.  It might be a good sanity check to add a test that uses `.execute('rollback')` as well to verify that the test assertions are correct, as it doesn't appear that any tests cover `NoticeReceived` today.

**Comment by jamadden** [comment]
OK. That's a lot more work than I was hoping for, but I can give it a shot 😄

**Comment by jamadden** [comment]
> The docs on this property show how to subscribe to it and the data that will be received.

The docs appear to be wrong. It says it gets an object with some properties, but in reality it gets a dict. Should I update the comment?

**Comment by jamadden** [comment]
OK, that wasn't so bad. Added a test that works on my machine.

**Comment by mfenniak** [comment]
Test looks great, thanks for adding that.  It hit a small flake8 error on the CI -- I'll take care of that for you.

**Comment by mfenniak** [comment]
👍 Sorry about the silly failure, line length really ideally shouldn't be such a big deal... in a comment... in a test file.

**Pull request merged**
