### PR TITLE
Update to latest postgresql releases

### PR DESCRIPTION
**Pull request by williamjmorenor**
Hi I am opening this pull request to use the current six version available in Fedora and Debian repos.

This pull request should fix:

#99  Having six library as dependency
#98 https://github.com/mfenniak/pg8000/issues/98
#96  RPM Packaging

Signed-off-by: William Moreno Reyes <williamjmorenor at fedoraproject.org>

### CODE REVIEW

**Comment by tlocke** [comment]
I've rebased these commits onto the latest master branch in my repo:

https://github.com/mfenniak/pg8000/compare/master...tlocke:master

So with these commits we have 'six' as a dependency. So if there are no objections I'll push this to the main repo.

**Comment by williamjmorenor** [comment]
Thanks for merging the unbundle of six.py, I have updated to latest postgresql releases in test.

**Comment by tlocke** [comment]
Thanks for updating those Postgres versions, I've pushed them to the main repo: https://github.com/mfenniak/pg8000/commit/6bb5b043fdca440ec2d69751c8e00db14786d1ce.

**Comment by williamjmorenor** [comment]
Thanks

**Pull request closed without merging**
